### ISSUE TITLE
Can't login to a newly built container.

### ISSUE THREAD

**Issue by ishiha** [devinsolutions/docker-taiga#4]
Thank you for the beautiful repository.
I tried it immediately, but could not log in with "admin: 123123".
Is this procedure something wrong?

```
git clone https://github.com/devinsolutions/docker-taiga.git taiga
cd taiga

vi docker-compose.advanced.yml
    - # - populate-db
    + - populate-db

docker-compose -f ./docker-compose.advanced.yml up -d
```

**Comment by lubo** [comment]
Hi @ishiha. Could provide more info, please? Did the `migrations` service exit successfully before you attempted to log in?

**Comment by ishiha** [comment]
@lubo Thanks for the reply. This is the log when Docker-compose is executed.

```
docker-compose -f docker-compose.advanced.yml up
WARNING: Some services (events, migrations, server) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Starting taiga_migrations_1 ... 
Starting taiga_broker_1 ... 
Starting taiga_events_1 ... 
Starting taiga_reverse-proxy_1 ... 
Starting taiga_server_1 ... 
Starting taiga_broker_1 ... done
Attaching to taiga_reverse-proxy_1, taiga_migrations_1, taiga_database_1, taiga_events_1, taiga_server_1, taiga_broker_1
database_1       | 
database_1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
database_1       | 
database_1       | 2019-12-22 16:11:32.768 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1       | 2019-12-22 16:11:32.768 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1       | 2019-12-22 16:11:32.772 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1       | 2019-12-22 16:11:32.787 UTC [27] LOG:  database system was shut down at 2019-12-22 16:11:18 UTC
database_1       | 2019-12-22 16:11:32.793 UTC [1] LOG:  database system is ready to accept connections
migrations_1     | Trying import local.py settings...
server_1         | Trying import local.py settings...
migrations_1     | System check identified some issues:
migrations_1     | 
migrations_1     | WARNINGS:
migrations_1     | ?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
migrations_1     | ?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
migrations_1     | ?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
migrations_1     | 
migrations_1     | System check identified 3 issues (4 silenced).
server_1         | System check identified some issues:
server_1         | 
server_1         | WARNINGS:
server_1         | ?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
server_1         | ?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
server_1         | ?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
server_1         | 
server_1         | System check identified 3 issues (4 silenced).
server_1         | Trying import local.py settings...
migrations_1     | Trying import local.py settings...
server_1         | Post-processed 'admin/css/dashboard.css' as 'admin/css/dashboard.7ac78187c567.css'
server_1         | Post-processed 'admin/css/base.css' as 'admin/css/base.31652d31b392.css'
server_1         | Post-processed 'admin/css/forms.css' as 'admin/css/forms.15ebfebbeb3d.css'
server_1         | Post-processed 'admin/css/widgets.css' as 'admin/css/widgets.5e372b41c483.css'
server_1         | Post-processed 'admin/css/rtl.css' as 'admin/css/rtl.4c867197b256.css'
server_1         | Post-processed 'admin/css/fonts.css' as 'admin/css/fonts.494e4ec545c9.css'
server_1         | Post-processed 'admin/css/changelists.css' as 'admin/css/changelists.f6dc691f8d62.css'
server_1         | Post-processed 'admin/css/login.css' as 'admin/css/login.a846c0e2ef65.css'
server_1         | Post-processed 'admin/css/dashboard.css' as 'admin/css/dashboard.7ac78187c567.css'
server_1         | Post-processed 'admin/css/base.css' as 'admin/css/base.6b517d0d5813.css'
server_1         | Post-processed 'admin/css/forms.css' as 'admin/css/forms.2003a066ae02.css'
server_1         | Post-processed 'admin/css/widgets.css' as 'admin/css/widgets.5e372b41c483.css'
server_1         | Post-processed 'admin/css/rtl.css' as 'admin/css/rtl.4c867197b256.css'
server_1         | Post-processed 'admin/css/fonts.css' as 'admin/css/fonts.494e4ec545c9.css'
server_1         | Post-processed 'admin/css/changelists.css' as 'admin/css/changelists.f6dc691f8d62.css'
server_1         | Post-processed 'admin/css/login.css' as 'admin/css/login.a846c0e2ef65.css'
server_1         | Post-processed 'admin/css/dashboard.css' as 'admin/css/dashboard.7ac78187c567.css'
server_1         | Post-processed 'admin/css/base.css' as 'admin/css/base.6b517d0d5813.css'
server_1         | Post-processed 'admin/css/forms.css' as 'admin/css/forms.2003a066ae02.css'
server_1         | Post-processed 'admin/css/widgets.css' as 'admin/css/widgets.5e372b41c483.css'
server_1         | Post-processed 'admin/css/rtl.css' as 'admin/css/rtl.4c867197b256.css'
server_1         | Post-processed 'admin/css/fonts.css' as 'admin/css/fonts.494e4ec545c9.css'
server_1         | Post-processed 'admin/css/changelists.css' as 'admin/css/changelists.f6dc691f8d62.css'
server_1         | Post-processed 'admin/css/login.css' as 'admin/css/login.a846c0e2ef65.css'
server_1         | 
server_1         | 0 static files copied to '/srv/taiga-back/static', 939 unmodified, 24 post-processed.
server_1         | [uWSGI] getting INI configuration from /usr/local/etc/uwsgi/uwsgi.ini
server_1         | *** Starting uWSGI 2.0.18 (64bit) on [Sun Dec 22 16:11:40 2019] ***
server_1         | compiled with version: 8.3.0 on 21 December 2019 11:08:15
server_1         | os: Linux-3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019
server_1         | nodename: b2e4a2730ede
server_1         | machine: x86_64
server_1         | clock source: unix
server_1         | pcre jit disabled
server_1         | detected number of CPU cores: 4
server_1         | current working directory: /opt/taiga-back
server_1         | detected binary path: /usr/local/bin/uwsgi
server_1         | *** dumping internal routing table ***
server_1         | [rule: 0] subject: path_info regexp: ^/favicon.ico$ action: goto:404
server_1         | [rule: 1] action: addheader:X-Content-Type-Options: nosniff
server_1         | [rule: 2] subject: path_info regexp: ^/((images|v-\d+)(/|$)|(conf.json|humans.txt|robots.txt)$) action: goto:front
server_1         | [rule: 3] subject: path_info regexp: ^/media(/|$) action: goto:media
server_1         | [rule: 4] subject: path_info regexp: ^/static(/|$) action: goto:static
server_1         | [rule: 5] action: addheader:X-Frame-Options: DENY
server_1         | [rule: 6] action: addheader:X-XSS-Protection: 1; mode=block
server_1         | [rule: 7] subject: path_info regexp: ^/(?!(admin|api)(/|$)) action: addheader:Cache-Control: no-cache, must-revalidate
server_1         | [rule: 8] subject: path_info regexp: ^/(?!(admin|api)(/|$)) action: static:/opt/taiga-front/index.html
server_1         | [rule: 9] action: last:
server_1         | [rule: 10] label: front
server_1         | [rule: 11] subject: path_info regexp: ^/(.*) action: rewrite:$1
server_1         | [rule: 12] subject: /opt/taiga-front/${PATH_INFO} func: isfile action: goto:front-file
server_1         | [rule: 13] action: goto:404
server_1         | [rule: 14] label: front-file
server_1         | [rule: 15] subject: path_info regexp: ^v-\d+/ action: addheader:Cache-Control: public, max-age=31536000
server_1         | [rule: 16] subject: path_info regexp: ^(?!v-\d+/) action: addheader:Cache-Control: no-cache, must-revalidate
server_1         | [rule: 17] action: static:/opt/taiga-front/${PATH_INFO}
server_1         | [rule: 18] label: media
server_1         | [rule: 19] subject: path_info regexp: ^/media/(.*) action: rewrite:$1
server_1         | [rule: 20] subject: /srv/taiga-back/media/${PATH_INFO} func: isfile action: static:/srv/taiga-back/media/${PATH_INFO}
server_1         | [rule: 21] action: goto:404
server_1         | [rule: 22] label: static
server_1         | [rule: 23] subject: path_info regexp: ^/static/(.*) action: rewrite:$1
server_1         | [rule: 24] subject: /srv/taiga-back/static/${PATH_INFO} func: isfile action: goto:static-file
server_1         | [rule: 25] action: goto:404
server_1         | [rule: 26] label: static-file
server_1         | [rule: 27] action: addheader:Cache-Control: public, max-age=31536000
server_1         | [rule: 28] action: static:/srv/taiga-back/static/${PATH_INFO}
server_1         | [rule: 29] label: 404
server_1         | [rule: 30] action: addheader:Cache-Control: no-cache, must-revalidate
server_1         | [rule: 31] action: break:404 Not Found
server_1         | *** end of the internal routing table ***
server_1         | chdir() to /opt/taiga-back
server_1         | your processes number limit is 1048576
server_1         | your memory page size is 4096 bytes
server_1         | detected max file descriptor number: 1048576
server_1         | building mime-types dictionary from file /etc/mime.types...1183 entry found
server_1         | lock engine: pthread robust mutexes
server_1         | thunder lock: disabled (you can enable it with --thunder-lock)
server_1         | uwsgi socket 0 bound to TCP address :8080 fd 3
server_1         | uwsgi socket 1 bound to TCP address :3031 fd 4
server_1         | Python version: 3.7.6 (default, Dec 21 2019, 08:28:11)  [GCC 8.3.0]
server_1         | *** Python threads support is disabled. You can enable it with --enable-threads ***
server_1         | Python main interpreter initialized at 0x565052cc96c0
server_1         | your server socket listen backlog is limited to 100 connections
server_1         | your mercy for graceful operations on workers is 60 seconds
server_1         | mapped 145808 bytes (142 KB) for 1 cores
server_1         | *** Operational MODE: single process ***
migrations_1     | Operations to perform:
migrations_1     |   Apply all migrations: admin, attachments, auth, bitbucket, contact, contenttypes, custom_attributes, djmail, easy_thumbnails, epics, external_apps, feedback, github, gitlab, gogs, history, issues, likes, milestones, notifications, projects, references, sessions, settings, tasks, timeline, users, userstorage, userstories, votes, webhooks, wiki
migrations_1     | Running migrations:
migrations_1     |   No migrations to apply.
server_1         | Trying import local.py settings...
broker_1         | 2019-12-22 16:11:42.316 [info] <0.8.0> Feature flags: list of feature flags found:
broker_1         | 2019-12-22 16:11:42.316 [info] <0.8.0> Feature flags: feature flag states written to disk: yes
broker_1         | 2019-12-22 16:11:42.392 [info] <0.292.0> 
broker_1         |  Starting RabbitMQ 3.7.23 on Erlang 22.2.1
broker_1         |  Copyright (C) 2007-2019 Pivotal Software, Inc.
broker_1         |  Licensed under the MPL.  See https://www.rabbitmq.com/
broker_1         | 
broker_1         |   ##  ##
broker_1         |   ##  ##      RabbitMQ 3.7.23. Copyright (C) 2007-2019 Pivotal Software, Inc.
broker_1         |   ##########  Licensed under the MPL.  See https://www.rabbitmq.com/
broker_1         |   ######  ##
broker_1         |   ##########  Logs: <stdout>
broker_1         | 
broker_1         |               Starting broker...
broker_1         | 2019-12-22 16:11:42.393 [info] <0.292.0> 
broker_1         |  node           : rabbit@localhost
broker_1         |  home dir       : /var/lib/rabbitmq
broker_1         |  config file(s) : /etc/rabbitmq/rabbitmq.conf
broker_1         |  cookie hash    : WJo4DKcQGSiQbKTbLAgKTg==
broker_1         |  log(s)         : <stdout>
broker_1         |  database dir   : /var/lib/rabbitmq/mnesia/rabbit@localhost
broker_1         | 2019-12-22 16:11:42.402 [info] <0.292.0> Running boot step pre_boot defined by app rabbit
broker_1         | 2019-12-22 16:11:42.402 [info] <0.292.0> Running boot step rabbit_core_metrics defined by app rabbit
broker_1         | 2019-12-22 16:11:42.402 [info] <0.292.0> Running boot step rabbit_alarm defined by app rabbit
broker_1         | 2019-12-22 16:11:42.406 [info] <0.298.0> Memory high watermark set to 1515 MiB (1589274214 bytes) of 3789 MiB (3973185536 bytes) total
broker_1         | 2019-12-22 16:11:42.411 [info] <0.300.0> Enabling free disk space monitoring
broker_1         | 2019-12-22 16:11:42.411 [info] <0.300.0> Disk free limit set to 50MB
broker_1         | 2019-12-22 16:11:42.419 [info] <0.292.0> Running boot step code_server_cache defined by app rabbit
broker_1         | 2019-12-22 16:11:42.420 [info] <0.292.0> Running boot step file_handle_cache defined by app rabbit
broker_1         | 2019-12-22 16:11:42.420 [info] <0.304.0> FHC read buffering:  OFF
broker_1         | 2019-12-22 16:11:42.420 [info] <0.304.0> FHC write buffering: ON
broker_1         | 2019-12-22 16:11:42.420 [info] <0.303.0> Limiting to approx 1048476 file handles (943626 sockets)
broker_1         | 2019-12-22 16:11:42.424 [info] <0.292.0> Running boot step worker_pool defined by app rabbit
broker_1         | 2019-12-22 16:11:42.424 [info] <0.293.0> Will use 4 processes for default worker pool
broker_1         | 2019-12-22 16:11:42.424 [info] <0.293.0> Starting worker pool 'worker_pool' with 4 processes in it
broker_1         | 2019-12-22 16:11:42.424 [info] <0.292.0> Running boot step database defined by app rabbit
broker_1         | 2019-12-22 16:11:42.431 [info] <0.292.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
broker_1         | 2019-12-22 16:11:42.453 [info] <0.292.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
broker_1         | 2019-12-22 16:11:42.453 [info] <0.292.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
broker_1         | 2019-12-22 16:11:42.453 [info] <0.292.0> Running boot step database_sync defined by app rabbit
broker_1         | 2019-12-22 16:11:42.453 [info] <0.292.0> Running boot step feature_flags defined by app rabbit
broker_1         | 2019-12-22 16:11:42.455 [info] <0.292.0> Running boot step codec_correctness_check defined by app rabbit
broker_1         | 2019-12-22 16:11:42.455 [info] <0.292.0> Running boot step external_infrastructure defined by app rabbit
broker_1         | 2019-12-22 16:11:42.455 [info] <0.292.0> Running boot step rabbit_registry defined by app rabbit
broker_1         | 2019-12-22 16:11:42.455 [info] <0.292.0> Running boot step rabbit_auth_mechanism_cr_demo defined by app rabbit
broker_1         | 2019-12-22 16:11:42.456 [info] <0.292.0> Running boot step rabbit_queue_location_random defined by app rabbit
broker_1         | 2019-12-22 16:11:42.456 [info] <0.292.0> Running boot step rabbit_event defined by app rabbit
broker_1         | 2019-12-22 16:11:42.456 [info] <0.292.0> Running boot step rabbit_auth_mechanism_amqplain defined by app rabbit
broker_1         | 2019-12-22 16:11:42.457 [info] <0.292.0> Running boot step rabbit_auth_mechanism_plain defined by app rabbit
broker_1         | 2019-12-22 16:11:42.457 [info] <0.292.0> Running boot step rabbit_exchange_type_direct defined by app rabbit
broker_1         | 2019-12-22 16:11:42.457 [info] <0.292.0> Running boot step rabbit_exchange_type_fanout defined by app rabbit
broker_1         | 2019-12-22 16:11:42.457 [info] <0.292.0> Running boot step rabbit_exchange_type_headers defined by app rabbit
broker_1         | 2019-12-22 16:11:42.457 [info] <0.292.0> Running boot step rabbit_exchange_type_topic defined by app rabbit
broker_1         | 2019-12-22 16:11:42.457 [info] <0.292.0> Running boot step rabbit_mirror_queue_mode_all defined by app rabbit
broker_1         | 2019-12-22 16:11:42.457 [info] <0.292.0> Running boot step rabbit_mirror_queue_mode_exactly defined by app rabbit
broker_1         | 2019-12-22 16:11:42.457 [info] <0.292.0> Running boot step rabbit_mirror_queue_mode_nodes defined by app rabbit
broker_1         | 2019-12-22 16:11:42.457 [info] <0.292.0> Running boot step rabbit_priority_queue defined by app rabbit
broker_1         | 2019-12-22 16:11:42.458 [info] <0.292.0> Priority queues enabled, real BQ is rabbit_variable_queue
broker_1         | 2019-12-22 16:11:42.458 [info] <0.292.0> Running boot step rabbit_queue_location_client_local defined by app rabbit
broker_1         | 2019-12-22 16:11:42.458 [info] <0.292.0> Running boot step rabbit_queue_location_min_masters defined by app rabbit
broker_1         | 2019-12-22 16:11:42.458 [info] <0.292.0> Running boot step kernel_ready defined by app rabbit
broker_1         | 2019-12-22 16:11:42.458 [info] <0.292.0> Running boot step rabbit_sysmon_minder defined by app rabbit
broker_1         | 2019-12-22 16:11:42.458 [info] <0.292.0> Running boot step rabbit_epmd_monitor defined by app rabbit
broker_1         | 2019-12-22 16:11:42.470 [info] <0.325.0> epmd monitor knows us, inter-node communication (distribution) port: 25672
broker_1         | 2019-12-22 16:11:42.470 [info] <0.292.0> Running boot step guid_generator defined by app rabbit
broker_1         | 2019-12-22 16:11:42.475 [info] <0.292.0> Running boot step rabbit_node_monitor defined by app rabbit
broker_1         | 2019-12-22 16:11:42.475 [info] <0.331.0> Starting rabbit_node_monitor
broker_1         | 2019-12-22 16:11:42.476 [info] <0.292.0> Running boot step delegate_sup defined by app rabbit
broker_1         | 2019-12-22 16:11:42.477 [info] <0.292.0> Running boot step rabbit_memory_monitor defined by app rabbit
broker_1         | 2019-12-22 16:11:42.477 [info] <0.292.0> Running boot step core_initialized defined by app rabbit
broker_1         | 2019-12-22 16:11:42.477 [info] <0.292.0> Running boot step upgrade_queues defined by app rabbit
broker_1         | 2019-12-22 16:11:42.499 [info] <0.292.0> Running boot step rabbit_connection_tracking defined by app rabbit
broker_1         | 2019-12-22 16:11:42.499 [info] <0.292.0> Running boot step rabbit_connection_tracking_handler defined by app rabbit
broker_1         | 2019-12-22 16:11:42.499 [info] <0.292.0> Running boot step rabbit_exchange_parameters defined by app rabbit
broker_1         | 2019-12-22 16:11:42.499 [info] <0.292.0> Running boot step rabbit_mirror_queue_misc defined by app rabbit
broker_1         | 2019-12-22 16:11:42.501 [info] <0.292.0> Running boot step rabbit_policies defined by app rabbit
broker_1         | 2019-12-22 16:11:42.502 [info] <0.292.0> Running boot step rabbit_policy defined by app rabbit
broker_1         | 2019-12-22 16:11:42.502 [info] <0.292.0> Running boot step rabbit_queue_location_validator defined by app rabbit
broker_1         | 2019-12-22 16:11:42.502 [info] <0.292.0> Running boot step rabbit_vhost_limit defined by app rabbit
broker_1         | 2019-12-22 16:11:42.502 [info] <0.292.0> Running boot step recovery defined by app rabbit
broker_1         | 2019-12-22 16:11:42.517 [info] <0.360.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@localhost/msg_stores/vhosts/DUUPSD51ILPPE6LUATO0IN63B' for vhost 'taiga' exists
broker_1         | 2019-12-22 16:11:42.521 [info] <0.360.0> Starting message stores for vhost 'taiga'
broker_1         | 2019-12-22 16:11:42.521 [info] <0.364.0> Message store "DUUPSD51ILPPE6LUATO0IN63B/msg_store_transient": using rabbit_msg_store_ets_index to provide index
broker_1         | 2019-12-22 16:11:42.523 [info] <0.360.0> Started message store of type transient for vhost 'taiga'
broker_1         | 2019-12-22 16:11:42.524 [info] <0.367.0> Message store "DUUPSD51ILPPE6LUATO0IN63B/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
broker_1         | 2019-12-22 16:11:42.526 [info] <0.360.0> Started message store of type persistent for vhost 'taiga'
broker_1         | 2019-12-22 16:11:42.528 [info] <0.292.0> Running boot step empty_db_check defined by app rabbit
broker_1         | 2019-12-22 16:11:42.528 [info] <0.292.0> Running boot step rabbit_looking_glass defined by app rabbit
broker_1         | 2019-12-22 16:11:42.528 [info] <0.292.0> Running boot step rabbit_core_metrics_gc defined by app rabbit
broker_1         | 2019-12-22 16:11:42.528 [info] <0.292.0> Running boot step background_gc defined by app rabbit
broker_1         | 2019-12-22 16:11:42.529 [info] <0.292.0> Running boot step connection_tracking defined by app rabbit
broker_1         | 2019-12-22 16:11:42.529 [info] <0.292.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@localhost
broker_1         | 2019-12-22 16:11:42.529 [info] <0.292.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@localhost
broker_1         | 2019-12-22 16:11:42.529 [info] <0.292.0> Running boot step routing_ready defined by app rabbit
broker_1         | 2019-12-22 16:11:42.529 [info] <0.292.0> Running boot step pre_flight defined by app rabbit
broker_1         | 2019-12-22 16:11:42.529 [info] <0.292.0> Running boot step notify_cluster defined by app rabbit
broker_1         | 2019-12-22 16:11:42.529 [info] <0.292.0> Running boot step networking defined by app rabbit
broker_1         | 2019-12-22 16:11:42.555 [info] <0.404.0> started TCP listener on [::]:5672
broker_1         | 2019-12-22 16:11:42.555 [info] <0.292.0> Running boot step direct_client defined by app rabbit
broker_1         |  completed with 0 plugins.
broker_1         | 2019-12-22 16:11:42.733 [info] <0.8.0> Server startup complete; 0 plugins started.
migrations_1     | Trying import local.py settings...
server_1         | WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x565052cc96c0 pid: 1 (default app)
server_1         | *** uWSGI is running in multiple interpreter mode ***
server_1         | spawned uWSGI master process (pid: 1)
server_1         | spawned uWSGI worker 1 (pid: 28, cores: 1)
server_1         | spawned 4 offload threads for uWSGI worker 1
migrations_1     | Installed 3 object(s) from 2 fixture(s)
taiga_migrations_1 exited with code 0
server_1         | [pid: 28|app: 0|req: 1/1] 127.0.0.1 () {24 vars in 267 bytes} [Sun Dec 22 16:12:02 2019] GET /api/v1/ => generated 5939 bytes in 210 msecs (HTTP/1.1 200) 14 headers in 894 bytes (1 switches on core 0)
```

Is there a problem here..?

```
migrations_1     | Operations to perform:
migrations_1     |   Apply all migrations: admin, attachments, auth, bitbucket, contact, contenttypes, custom_attributes, djmail, easy_thumbnails, epics, external_apps, feedback, github, gitlab, gogs, history, issues, likes, milestones, notifications, projects, references, sessions, settings, tasks, timeline, users, userstorage, userstories, votes, webhooks, wiki
migrations_1     | Running migrations:
migrations_1     |   No migrations to apply.
```

**Comment by lubo** [comment]
So, the logs indicate all the migrations were applied and the fixture which creates admin account was loaded. So, could you elaborate on why are you unable to login? Do you get an error message on the login screen? If so, could you post logs from the browser console, please?

**Comment by ishiha** [comment]
Sorry about the long message.
An error message was also displayed on the login screen.

```
Oops, something happened ...
According to our Oompa Loompas, your username / email or password are incorrect.
```

Also, an error message was output to the browser console.

```
Firefox can’t establish a connection to the server at ws://127.0.0.1:8080/events. app.js:3242:16
WebSocket error: [object Event] angular.js:14195
    o Angular
    onError app.js:3485
    r Lodash
```

Should I change `"eventsUrl": "ws://127.0.0.1:8080/events"` of `docker-compose/front.json`?

**Comment by lubo** [comment]
AFAIK these two messages are unrelated, although it seems like the requests made by the frontend are not routed properly, so it looks like there's something wrong with your setup. Did you change anything besides uncommenting `- populate-db` in `docker-compose.advanced.yml`? How does a response to the login requests look like?

**Comment by ishiha** [comment]
hmm,I have not changed anything other than `- populate-db`. 
I tried again with`git clone`, but the result was the same.
Browser console logs had the same result.
```
Firefox can’t establish a connection to the server at ws://127.0.0.1:8080/events. app.js:3242:16
The connection to ws://127.0.0.1:8080/events was interrupted while the page was loading. app.js:3242:16
```

I found a [similar issue on github](https://github.com/taigaio/taiga-back/issues/1244) of Taiga.io and fixed it, but it was not solved.
I’ll do some more research.

**Comment by lubo** [comment]
It'd be really helpful if you posted a response to a login request as I wrote in the previous post. Also, which versions of Docker and Docker Compose do you use?

**Comment by ishiha** [comment]
This is the http request and response when I log in.

```
POST /api/v1/auth HTTP/1.1
Host: xxx.xx.xxx.xxx:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0
Accept: application/json, text/plain, */*
Accept-Language: en
Accept-Encoding: gzip, deflate
Content-Type: application/json
X-Session-Id: 878e310b2f042c44de9edeb0bef3fde887f8ac1f
Content-Length: 56
Origin: http://xxx.xx.xxx.xxx:8080
Connection: keep-alive
Referer: http://xxx.xx.xxx.xxx:8080/login?next=%252Fdiscover
```

```
HTTP/1.1 400 Bad Request
Server: nginx/1.17.6
Date: Mon, 23 Dec 2019 12:38:16 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 26
Connection: keep-alive
Vary: Accept-Language
Content-Language: en
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,DELETE,PATCH,HEAD
Access-Control-Allow-Headers: content-type,x-requested-with,authorization,accept-encoding,x-disable-pagination,x-lazy-pagination,x-host,x-session-id,set-orders
Access-Control-Expose-Headers: x-pagination-count,x-paginated,x-paginated-by,x-pagination-current,x-pagination-next,x-pagination-prev,x-site-host,x-site-register,taiga-info-total-opened-milestones,taiga-info-total-closed-milestones,taiga-info-project-memberships,taiga-info-project-is-private,taiga-info-order-updated
Access-Control-Max-Age: 3600
Access-Control-Allow-Credentials: true
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```
Docker version is `1.13.1, build 7f2769b/1.13.1`
Docker-compose version is `1.18.0, build 8dd22a9`
Thank you.

**Comment by lubo** [comment]
From the response I see the request hits the server, but the server most likely rejects it due to invalid credentials. I can't confirm that because you didn't include the request and response bodies… Anyway, you should double-check the credentials. The default password is `123123`, without the leading space as you wrote in your initial comment. Also, Docker and Docker Compose versions you use are pretty old, so I can't rule out this isn't caused by an obscure bug in one of them. You should upgrade to the recent versions. With that being said, I don't see a good indication that there's something wrong with this image nor the example compose file, so I'm closing this issue. If you find out what's the problem here, I might be able to help, but the information you've provided so far is not enough.
